---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install dirmngr in order to be able to install the apt signing key
  apt:
    pkg:
      - dirmngr
- name: Add PPA Key for deadsnakes
  apt_key:
    id: F23C5A6CF475977595C89F51BA6932366A755776
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/deadsnakes-ppa.gpg
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP '{{ "VERSION" if ansible_distribution == "Debian" else "UBUNTU" }}_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
- name: Add deadsnakes PPA
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/deadsnakes-ppa.gpg] https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu {{ distro.stdout }} main"
    state: present
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install Python and associated packages
  apt:
    pkg:
      - python3
      - python3-dev
      - python3-venv
      - python3.10
      - python3.10-dev
      - python3.10-venv
      - python3-lxml
      - pipenv
      - tox
